---

- name: 'Provision monitorable hosts'
  hosts: system 
  gather_facts: true
  become: true
  roles:
    - common
    - node-exporter

- name: 'Provision monitorting hosts'
  hosts: monitoring
  gather_facts: true
  become: true
  roles:
    - common
    - docker-host
    - docker-prometheus
